### ISSUE TITLE
Can't run app in simulator/device because of error "Library not loaded: mokoMvvmFlowSwiftUI"

### ISSUE THREAD

**Issue by nathalia2112** [icerockdev/moko-mvvm#187] opened 2022-07-04 18:50 UTC
I've created MultiPlatformLibrary (KMM) and I'm using it in my ios project.
I also installed mokoMvvmFlowSwiftUI using pods but when I try to run my project in simulator or in my device I get this error:

```
dyld[19421]: Library not loaded: @rpath/mokoMvvmFlowSwiftUI.framework/mokoMvvmFlowSwiftUI
Referenced from: 
/Users/myuser/Library/Developer/CoreSimulator/Devices/device/data/Containers/Bundle/Application/ap/Project.app/Project  
Reason: tried: '/Users/myuser/Library/Developer/Xcode/DerivedData/Project-id/Build/Products/Debug-iphonesimulator/mokoMvvmFlowSwiftUI.framework/mokoMvvmFlowSwiftUI' (no such file), 
'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/mokoMvvmFlowSwiftUI.framework/mokoMvvmFlowSwiftUI' (no such file), 
'/usr/lib/swift/mokoMvvmFlowSwiftUI.framework/mokoMvvmFlowSwiftUI' (no such file)
(lldb) 
...
```

**Comment by jmoreirawk** [comment] 2022-08-26 15:54
I'm probably a bit too late, but I fixed this problem using the solution on this [StackOverflow question](https://stackoverflow.com/a/55764750/15636543). Just needed to add the lib onto the Frameworks, Libraries and Embedded Content.

**Comment by Alex009** [comment] 2022-11-21 12:03
duplicate of #186

**Closed by Alex009** 2022-11-21 12:03 UTC
